---
- name: Configure Manage Nodes
  hosts: all
  become: true

  vars_prompt:
    - name: user_name
      prompt: Enter username

  tasks:
    - name: Install python3 and pip3 on Ubuntu
      apt:
        name:
          - python3
          - python3-pip
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install python3 and pip3 on CentOS
      dnf:
        name:
          - python3
          - python3-pip
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Use pip3 as default pip on Ubuntu
      command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
      when: ansible_distribution == "Ubuntu"

    - name: Use python3 as default python on Ubuntu
      command: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
      when: ansible_distribution == "Ubuntu"

    - name: Use pip3 as default pip on CentOS
      command: alternatives --set pip /usr/bin/pip3
      when: ansible_distribution == "CentOS"

    - name: Use python3 as default python on CentOS
      command: alternatives --set python /usr/bin/python3
      when: ansible_distribution == "CentOS"




    - name: Install Java on Ubuntu
      apt:
        name:
          - openjdk-11-jre
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Java on CentOS
      dnf:
        name:
          - java-11-openjdk
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Create Motd
      template:
        src: motd.j2
        dest: /etc/motd

    - name: Create user
      user:
        name: "{{ user_name }}"
        state: present
        createhome: yes
      become: yes
